export type ToolCategory = "pdf" | "image";

export type ToolDefinition = {
  id: string;
  name: string;
  description: string;
  icon: string;
  category: ToolCategory;
  href: string;
  color: string;
};

export const tools: ToolDefinition[] = [
  {
    id: "compress",
    name: "Compress PDF",
    description: "Reduce PDF size for faster sharing and cleaner uploads.",
    icon: "FileArchive",
    category: "pdf",
    href: "/pdf/compress",
    color: "sky",
  },
  {
    id: "merge",
    name: "Merge PDFs",
    description: "Combine multiple PDF files into a single organized document.",
    icon: "Files",
    category: "pdf",
    href: "/pdf/merge",
    color: "cyan",
  },
  {
    id: "split",
    name: "Split PDF",
    description: "Extract selected pages or break a large PDF into smaller parts.",
    icon: "Scissors",
    category: "pdf",
    href: "/pdf/split",
    color: "indigo",
  },
  {
    id: "rotate",
    name: "Rotate PDF",
    description: "Fix page orientation in seconds before downloading the final file.",
    icon: "RotateCw",
    category: "pdf",
    href: "/pdf/rotate",
    color: "violet",
  },
  {
    id: "extract-text",
    name: "Extract Text",
    description: "Pull searchable text from PDF pages while preserving layout.",
    icon: "FileText",
    category: "pdf",
    href: "/pdf/extract-text",
    color: "slate",
  },
  {
    id: "to-images",
    name: "PDF to Images",
    description: "Turn each PDF page into crisp PNG or JPG output.",
    icon: "Images",
    category: "pdf",
    href: "/pdf/to-images",
    color: "emerald",
  },
  {
    id: "images-to-pdf",
    name: "Images to PDF",
    description: "Create a clean, shareable PDF from one or more images.",
    icon: "FileImage",
    category: "pdf",
    href: "/pdf/images-to-pdf",
    color: "rose",
  },
  {
    id: "office-to-pdf",
    name: "Office to PDF",
    description: "Convert Word, Excel, or PowerPoint files into PDF format.",
    icon: "FileSpreadsheet",
    category: "pdf",
    href: "/pdf/office-to-pdf",
    color: "amber",
  },
  {
    id: "protect",
    name: "Protect PDF",
    description: "Add password protection for secure document sharing.",
    icon: "Lock",
    category: "pdf",
    href: "/pdf/protect",
    color: "fuchsia",
  },
  {
    id: "decrypt",
    name: "Decrypt PDF",
    description: "Remove PDF password protection when you have access.",
    icon: "Unlock",
    category: "pdf",
    href: "/pdf/decrypt",
    color: "teal",
  },
  {
    id: "convert",
    name: "Convert Image",
    description: "Convert images between JPG, PNG, WEBP, TIFF, and AVIF.",
    icon: "RefreshCw",
    category: "image",
    href: "/image/convert",
    color: "sky",
  },
  {
    id: "resize",
    name: "Resize Image",
    description: "Resize for web, documents, and batch workflows with clean output.",
    icon: "Expand",
    category: "image",
    href: "/image/resize",
    color: "emerald",
  },
  {
    id: "compress",
    name: "Compress Image",
    description: "Reduce file size without losing more quality than necessary.",
    icon: "FileArchive",
    category: "image",
    href: "/image/compress",
    color: "cyan",
  },
  {
    id: "crop",
    name: "Crop Image",
    description: "Trim to the exact area you need with pixel-level control.",
    icon: "Crop",
    category: "image",
    href: "/image/crop",
    color: "rose",
  },
  {
    id: "rotate",
    name: "Rotate Image",
    description: "Rotate photos and artwork with quick angle adjustments.",
    icon: "RotateCw",
    category: "image",
    href: "/image/rotate",
    color: "violet",
  },
  {
    id: "watermark",
    name: "Watermark",
    description: "Apply branded text watermarks before publishing or sharing.",
    icon: "Stamp",
    category: "image",
    href: "/image/watermark",
    color: "amber",
  },
  {
    id: "remove-background",
    name: "Remove Background",
    description: "Cut out the subject and export with transparency.",
    icon: "Eraser",
    category: "image",
    href: "/image/remove-background",
    color: "fuchsia",
  },
  {
    id: "ocr",
    name: "OCR Image",
    description: "Extract readable text from screenshots, scans, and photos.",
    icon: "ScanSearch",
    category: "image",
    href: "/image/ocr",
    color: "teal",
  },
  {
    id: "batch-resize",
    name: "Batch Resize",
    description: "Resize many images at once by uploading a single zip archive.",
    icon: "Layers",
    category: "image",
    href: "/image/batch-resize",
    color: "indigo",
  },
  {
    id: "info",
    name: "Image Info",
    description: "Inspect dimensions, bands, format, and file size instantly.",
    icon: "Info",
    category: "image",
    href: "/image/info",
    color: "slate",
  },
];

export const pdfTools = tools.filter((tool) => tool.category === "pdf");
export const imageTools = tools.filter((tool) => tool.category === "image");
